In [45]:
import keras
from keras import layers
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error


In [46]:
df = pd.read_csv("final.csv")
df

rashod_name  year       y1    id  building_year  object_square  \
0            27751  2016   103.08     0           1980          217.7   
1            27751  2016   103.08     0           1980          217.7   
2            27751  2016   103.08     0           1980          217.7   
3            27751  2016   103.08     0           1980          217.7   
4            27751  2016   103.08     0           1980          217.7   
...            ...   ...      ...   ...            ...            ...   
29476        29480  2021  8779.34  2130           1994          783.5   
29477        29480  2021  1847.78  2130           1994          783.5   
29478        29480  2021   751.40  2130           1994          783.5   
29479        29480  2021  1249.12  2130           1994          783.5   
29480        29480  2021   234.33  2130           1994          783.5   

       building_square     balance  revaluation  depreciation  residual_value  \
0                217.7  1638812.21    937438.23     591497.66      1047314.55   
1                217.7  1638812.21    937438.23     596414.09      1042398.12   
2                217.7  1638812.21    937438.23     601330.52      1037481.69   
3                217.7  1638812.21    937438.23     606246.95      1032565.26   
4                217.7  1638812.21    937438.23     591497.66      1047314.55   
...                ...         ...          ...           ...             ...   
29476            783.5  3732828.27   1619966.80    1014084.97      2718743.30   
29477            783.5  3732828.27   1619966.80    1014084.97      2718743.30   
29478            783.5  3732828.27   1619966.80    1014084.97      2718743.30   
29479            783.5  3732828.27   1619966.80    1014084.97      2718743.30   
29480            783.5  3732828.27   1619966.80    1014084.97      2718743.30   

       technical_condition  quarter  otdel   city  
0                    29480        1  28240   5412  
1                    29480        2  28240   5412  
2                    29480        3  28240   5412  
3                    29480        4  28240   5412  
4                    29480        1  28240   5412  
...                    ...      ...    ...    ...  
29476                29480        4  29480  29480  
29477                29480        4  29480  29480  
29478                29480        4  29480  29480  
29479                29480        4  29480  29480  
29480                29480        4  29480  29480  

[29481 rows x 15 columns]

In [47]:
df.corr()

rashod_name      year        y1        id  building_year  \
rashod_name             1.000000  0.281030  0.045035  0.264235       0.175801   
year                    0.281030  1.000000 -0.008823  0.850717       0.125516   
y1                      0.045035 -0.008823  1.000000  0.001148       0.034825   
id                      0.264235  0.850717  0.001148  1.000000       0.086870   
building_year           0.175801  0.125516  0.034825  0.086870       1.000000   
object_square          -0.088142 -0.065690  0.088445 -0.109796      -0.154307   
building_square        -0.088142 -0.065690  0.088445 -0.109796      -0.154307   
balance                -0.131060  0.072935  0.040635  0.102913      -0.020446   
revaluation            -0.019305 -0.023355  0.082878  0.006930       0.008318   
depreciation           -0.019927  0.062131  0.082708  0.051678      -0.254782   
residual_value         -0.018195  0.061013  0.025852  0.067751      -0.158832   
technical_condition     0.123215  0.084402  0.022694  0.041651      -0.045611   
quarter                 0.035883  0.020023  0.006677  0.075173       0.002014   
otdel                   0.169103  0.087680  0.032887  0.045740       0.014412   
city                    0.180029  0.208936  0.010946  0.460251      -0.053112   

                     object_square  building_square   balance  revaluation  \
rashod_name              -0.088142        -0.088142 -0.131060    -0.019305   
year                     -0.065690        -0.065690  0.072935    -0.023355   
y1                        0.088445         0.088445  0.040635     0.082878   
id                       -0.109796        -0.109796  0.102913     0.006930   
building_year            -0.154307        -0.154307 -0.020446     0.008318   
object_square             1.000000         1.000000  0.246148     0.611754   
building_square           1.000000         1.000000  0.246148     0.611754   
balance                   0.246148         0.246148  1.000000     0.163333   
revaluation               0.611754         0.611754  0.163333     1.000000   
depreciation              0.684217         0.684217  0.241550     0.504056   
residual_value            0.421326         0.421326  0.408964     0.445928   
technical_condition       0.099009         0.099009  0.094225     0.104084   
quarter                   0.013634         0.013634 -0.041225    -0.006842   
otdel                     0.048694         0.048694 -0.172198     0.020448   
city                     -0.180899        -0.180899  0.004103    -0.084277   

                     depreciation  residual_value  technical_condition  \
rashod_name             -0.019927       -0.018195             0.123215   
year                     0.062131        0.061013             0.084402   
y1                       0.082708        0.025852             0.022694   
id                       0.051678        0.067751             0.041651   
building_year           -0.254782       -0.158832            -0.045611   
object_square            0.684217        0.421326             0.099009   
building_square          0.684217        0.421326             0.099009   
balance                  0.241550        0.408964             0.094225   
revaluation              0.504056        0.445928             0.104084   
depreciation             1.000000        0.640815             0.138809   
residual_value           0.640815        1.000000             0.146831   
technical_condition      0.138809        0.146831             1.000000   
quarter                  0.058832       -0.012529            -0.058514   
otdel                    0.023158        0.108233             0.214529   
city                    -0.071446        0.073377             0.087353   

                      quarter     otdel      city  
rashod_name          0.035883  0.169103  0.180029  
year                 0.020023  0.087680  0.208936  
y1                   0.006677  0.032887  0.010946  
id                   0.075173  0.045740  0.460251  
building_year        0.002014 

In [48]:
df.columns

Index(['rashod_name', 'year', 'y1', 'id', 'building_year', 'object_square',
       'building_square', 'balance', 'revaluation', 'depreciation',
       'residual_value', 'technical_condition', 'quarter', 'otdel', 'city'],
      dtype='object')

In [49]:
df.dtypes

rashod_name              int64
year                     int64
y1                     float64
id                       int64
building_year            int64
object_square          float64
building_square        float64
balance                float64
revaluation            float64
depreciation           float64
residual_value         float64
technical_condition      int64
quarter                  int64
otdel                    int64
city                     int64
dtype: object

In [50]:
y = np.array(df["y1"])
y

array([ 103.08,  103.08,  103.08, ...,  751.4 , 1249.12,  234.33])

In [51]:
df = df.drop(["y1"], axis=1)
x = np.array(df)
x

array([[2.7751e+04, 2.0160e+03, 0.0000e+00, ..., 1.0000e+00, 2.8240e+04,
        5.4120e+03],
       [2.7751e+04, 2.0160e+03, 0.0000e+00, ..., 2.0000e+00, 2.8240e+04,
        5.4120e+03],
       [2.7751e+04, 2.0160e+03, 0.0000e+00, ..., 3.0000e+00, 2.8240e+04,
        5.4120e+03],
       ...,
       [2.9480e+04, 2.0210e+03, 2.1300e+03, ..., 4.0000e+00, 2.9480e+04,
        2.9480e+04],
       [2.9480e+04, 2.0210e+03, 2.1300e+03, ..., 4.0000e+00, 2.9480e+04,
        2.9480e+04],
       [2.9480e+04, 2.0210e+03, 2.1300e+03, ..., 4.0000e+00, 2.9480e+04,
        2.9480e+04]])

In [52]:
layer = keras.layers.Normalization(axis=None)
layer.adapt(x)

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=228)
x_test

array([[2.9447e+04, 2.0210e+03, 2.0610e+03, ..., 3.0000e+00, 2.9402e+04,
        2.9397e+04],
       [2.9185e+04, 2.0160e+03, 2.1000e+02, ..., 1.0000e+00, 2.9402e+04,
        2.8688e+04],
       [2.7751e+04, 2.0160e+03, 3.0000e+01, ..., 2.0000e+00, 2.8240e+04,
        2.5888e+04],
       ...,
       [2.7751e+04, 2.0170e+03, 2.7000e+01, ..., 3.0000e+00, 2.8240e+04,
        5.4120e+03],
       [2.7751e+04, 2.0160e+03, 2.2000e+01, ..., 1.0000e+00, 2.8240e+04,
        5.4120e+03],
       [2.9185e+04, 2.0160e+03, 2.9400e+02, ..., 1.0000e+00, 2.9402e+04,
        1.4469e+04]])

In [54]:
model = keras.Sequential()
model.add(layers.Input(shape=x_train.shape[-1]))
model.add(layer)
model.add(layers.Dense(32, activation="relu"))
model.add(layers.Dense(64, activation="relu"))
model.add(layers.Dense(128, activation="relu"))
model.add(layers.Dense(32, activation="relu"))
model.add(layers.Dense(1, activation="relu"))
model.summary()
model.compile(loss="mse", optimizer="adam", metrics=["mean_absolute_percentage_error"])

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization_3 (Normalizat  (None, 14)               3         
 ion)                                                            
                                                                 
 dense_10 (Dense)            (None, 32)                480       
                                                                 
 dense_11 (Dense)            (None, 64)                2112      
                                                                 
 dense_12 (Dense)            (None, 128)               8320      
                                                                 
 dense_13 (Dense)            (None, 32)                4128      
                                                                 
 dense_14 (Dense)            (None, 1)                 33        
                                                      

In [55]:
model.fit(x=x_train, y=y_train, epochs=200, verbose=1)

Epoch 1/200
737/737 [==============================] - 1s 941us/step - loss: 199455440896.0000 - mean_absolute_percentage_error: 158198.9688
Epoch 2/200
737/737 [==============================] - 1s 870us/step - loss: 197561499648.0000 - mean_absolute_percentage_error: 250245.9219
Epoch 3/200
737/737 [==============================] - 1s 874us/step - loss: 197300994048.0000 - mean_absolute_percentage_error: 263485.6562
Epoch 4/200
737/737 [==============================] - 1s 910us/step - loss: 197000101888.0000 - mean_absolute_percentage_error: 277394.5938
Epoch 5/200
737/737 [==============================] - 1s 879us/step - loss: 196724948992.0000 - mean_absolute_percentage_error: 266071.5938
Epoch 6/200
737/737 [==============================] - 1s 875us/step - loss: 196534861824.0000 - mean_absolute_percentage_error: 270424.8438
Epoch 7/200
737/737 [==============================] - 1s 902us/step - loss: 196319428608.0000 - mean_absolute_percentage_error: 269986.9375
Epoch 8/200
7

In [56]:
model.evaluate(x=x_train, y=y_train)

737/737 [==============================] - 1s 690us/step - loss: 192124076032.0000 - mean_absolute_percentage_error: 234588.5938


[192124076032.0, 234588.59375]

In [57]:
prediction = model.predict(x_test)

185/185 [==============================] - 0s 636us/step


In [58]:
prediction

array([[79612.39 ],
       [53565.8  ],
       [19020.77 ],
       ...,
       [79859.   ],
       [44401.7  ],
       [79757.234]], dtype=float32)

In [59]:
y_test

array([  258.91, 97932.94,   571.3 , ...,   736.87, 22642.74,  9812.99])

In [60]:
score = mean_absolute_percentage_error(y_pred=prediction, y_true=y_test)
score

1507.1795500286562

In [62]:
model.save("Model")

INFO:tensorflow:Assets written to: Model\assets


INFO:tensorflow:Assets written to: Model\assets
